/** Pure combined-plan contracts; real transaction/migration tests live in scripts/scheme-bills-integration.ts. */
import assert from "node:assert/strict";
import { adminPlanBills, soPlanBills, allowedSchemeBillCounts, assertBillParts, assertBillTotals, combinedPresetValueErrors, schemeBillLimitError, splitBillAmount, billSchedule } from "@/lib/scheme-bills";
import { initialBillEditor, initialProductBillEditor, rebalanceBills, billEditorPayload, schemeTargetQuantitySummary, productBillingForProceedingUnits, recomputeProductBillEditor } from "./scheme-bill-fields";
import type { SchemePlan } from "./scheme-detail-dialog";
import { formatSchemeDate, parseSchemeDate } from "@/lib/utils";
const rules = [30,70].map((value,i) => ({ installmentNumber:i+1, calculationType:"PERCENTAGE", value, daysAfterBillingDate:i*30 }));
let passed=0;
function test(name:string,run:()=>void){run();passed++;console.log(`PASS ${name}`);}
const plan = (instances:number):SchemePlan => ({ numberOfSchemes:instances, billing:{billMode:false,locked:false,legacySchedules:false,soBillCount:null,adminBillCount:null,soAmountWithoutGST:null,soAmountWithGST:null,amountWithoutGST:null,amountWithGST:null,defaultAmountWithoutGST:"80000",defaultAmountWithGST:"100000",bookingAmount:null,bookingBillNumber:null,bills:[]} } as unknown as SchemePlan);
for(const [instances,count] of [[1,1],[4,1],[4,2],[4,5]])test(`${instances} instances + ${count} bills remains one combined billing object`,()=>{const row=rebalanceBills(initialBillEditor(plan(instances),false),{billCount:count});assert.equal(row.bills.length,count);assert.equal(row.amountWithGST,"100000");assert.equal(row.bills.reduce((sum,b)=>sum+Number(b.amountWithGST),0),100000);assert(!("instanceNumber" in billEditorPayload(row,false)));});
test("100000 / 2 = 50000 + 50000",()=>assert.deepEqual(splitBillAmount("100000",2),["50000.00","50000.00"]));
for (const [maximum, expected] of [[1, [1]], [3, [1, 2, 3]], [5, [1, 2, 3, 4, 5]]] as const)
  test(`Scheme Master maximum ${maximum} exposes only 1 through ${maximum}`, () => assert.deepEqual(allowedSchemeBillCounts(maximum), expected));
test("Scheme Master bill maximum is enforced independently of the global 1–5 boundary",()=>{
  assert.equal(schemeBillLimitError(3, 3), null);
  assert.match(schemeBillLimitError(4, 3)!, /Scheme Master limit of 3/);
  assert.match(schemeBillLimitError(0, 3)!, /positive whole number/);
  assert.match(schemeBillLimitError(-1, 3)!, /positive whole number/);
  assert.match(schemeBillLimitError(1.5, 3)!, /positive whole number/);
});
test("legacy Scheme rows retain the old maximum of five and an existing saved count remains renderable",()=>{
  assert.deepEqual(allowedSchemeBillCounts(undefined), [1, 2, 3, 4, 5]);
  assert.deepEqual(allowedSchemeBillCounts(3, 5), [1, 2, 3, 5]);
  assert.equal(schemeBillLimitError(5, 3, 5), null);
  assert.match(schemeBillLimitError(4, 3, 5)!, /Scheme Master limit of 3/);
});
test("100 / 3 assigns the exact paise remainder to final bill",()=>assert.deepEqual(splitBillAmount("100",3),["33.33","33.33","33.34"]));
test("0.05 / 3 uses integer paise without fractional loss",()=>assert.deepEqual(splitBillAmount("0.05",3),["0.01","0.01","0.03"]));
test("Admin combined override rebalances both totals without multiplying instances",()=>{let row=initialBillEditor(plan(4),true);row=rebalanceBills(row,{billCount:2,amountWithGST:"118000",amountWithoutGST:"100000"});assert.equal(row.bills[0].amountWithGST,"59000.00");assert.equal(row.bills[1].amountWithoutGST,"50000.00");});
test("SO combined totals cannot be below their corresponding preset totals",()=>{const preset={amountWithoutGST:"80000",amountWithGST:"100000"};assert.deepEqual(combinedPresetValueErrors({amountWithoutGST:"80000",amountWithGST:"100000"},preset),[]);assert.deepEqual(combinedPresetValueErrors({amountWithoutGST:"81000",amountWithGST:"101000"},preset),[]);assert.match(combinedPresetValueErrors({amountWithoutGST:"79999.99",amountWithGST:"100000"},preset)[0],/Without GST.*₹80,000/);assert.match(combinedPresetValueErrors({amountWithoutGST:"80000",amountWithGST:"99999.99"},preset)[0],/With GST.*₹1,00,000/);});
test("changing count preserves remaining part dates and rebalances values",()=>{const row=initialBillEditor(plan(4),false);row.bills[0].soBillDate="2026-09-12";const next=rebalanceBills(row,{billCount:3});assert.equal(next.bills[0].soBillDate,"2026-09-12");assert.equal(next.bills[2].amountWithGST,"33333.34");assert.equal(rebalanceBills(next,{billCount:1}).bills[0].amountWithGST,"100000.00");});
test("Product Quantity mode retains its automatic final committed quantity",()=>{const p=plan(1);p.productBilling={active:true,mode:"QUANTITY_TARGET",products:[{productId:"p",name:"P",committedQty:100,rateWithoutGST:10,rateWithGST:12}],bills:[]};const row=initialProductBillEditor(p,false);assert.equal(row.bills[0].products?.[0].qty,"100");assert.equal(row.amountWithoutGST,"1000.00");});
test("Options Value mode starts without a predefined product quantity",()=>{const p=plan(1);p.productBilling={active:true,mode:"VALUE_TARGET",products:[{productId:"p",name:"P",committedQty:null,rateWithoutGST:10,rateWithGST:12}],bills:[]};const row=initialProductBillEditor(p,false);assert.equal(row.bills[0].products?.[0].qty,"");assert.equal(row.amountWithoutGST,"0.00");});
test("Fixed Product Quantity Scheme Details uses one compact comma-separated target summary",()=>{const p=plan(1);p.productBilling={active:true,mode:"QUANTITY_TARGET",products:[{productId:"adam",name:"ADAM",committedQty:100,rateWithoutGST:10,rateWithGST:12},{productId:"agora",name:"AGORA",committedQty:200,rateWithoutGST:20,rateWithGST:24},{productId:"abc",name:"ABC",committedQty:150,rateWithoutGST:30,rateWithGST:36}],bills:[]};assert.equal(schemeTargetQuantitySummary(p),"ADAM 100, AGORA 200, ABC 150");});
test("Options Product Quantity Scheme Details follows the selected option snapshot",()=>{const option1=plan(1),option2=plan(1);option1.productBilling={active:true,mode:"QUANTITY_TARGET",products:[{productId:"adam",name:"ADAM",committedQty:100,rateWithoutGST:10,rateWithGST:12}],bills:[]};option2.productBilling={active:true,mode:"QUANTITY_TARGET",products:[{productId:"adam",name:"ADAM",committedQty:200,rateWithoutGST:10,rateWithGST:12}],bills:[]};assert.equal(schemeTargetQuantitySummary(option1),"ADAM 100");assert.equal(schemeTargetQuantitySummary(option2),"ADAM 200");});
test("Fixed Product Quantity Scheme Details and bill remainder scale to three proceeding units",()=>{const p=plan(3);const base={active:true as const,mode:"QUANTITY_TARGET" as const,products:[{productId:"adam",name:"ADAM",committedQty:300,perSchemeCommittedQty:100,rateWithoutGST:10,rateWithGST:12},{productId:"agora",name:"AGORA",committedQty:600,perSchemeCommittedQty:200,rateWithoutGST:20,rateWithGST:24}],bills:[]};p.productBilling=productBillingForProceedingUnits(base,3);assert.equal(schemeTargetQuantitySummary(p),"ADAM 300, AGORA 600");const row=initialProductBillEditor(p,false);assert.deepEqual(row.bills[0].products?.map(x=>x.qty),["300","600"]);});
test("4 to 2 split recomputes the current Product Quantity target without including Future Draft",()=>{const p=plan(4);const base={active:true as const,mode:"QUANTITY_TARGET" as const,products:[{productId:"adam",name:"ADAM",committedQty:400,perSchemeCommittedQty:100,rateWithoutGST:10,rateWithGST:12}],bills:[]};p.productBilling=base;const initial=initialProductBillEditor(p,false);const proceeding=productBillingForProceedingUnits(base,2);const row=recomputeProductBillEditor(initial,proceeding,false);assert.equal(proceeding.products[0].committedQty,200);assert.equal(row.bills[0].products?.[0].qty,"200");});
test("historical Product Quantity snapshots are totals and are never scaled again",()=>{const historical={active:true as const,mode:"QUANTITY_TARGET" as const,products:[{productId:"adam",name:"ADAM",committedQty:300,rateWithoutGST:10,rateWithGST:12}],bills:[]};assert.equal(productBillingForProceedingUnits(historical,3).products[0].committedQty,300);});
test("Value Based Scheme Details never invents a target quantity",()=>{const fixed=plan(1),options=plan(1);for(const p of [fixed,options])p.productBilling={active:true,mode:"VALUE_TARGET",products:[{productId:"adam",name:"ADAM",committedQty:null,rateWithoutGST:10,rateWithGST:12}],bills:[]};assert.equal(schemeTargetQuantitySummary(fixed),null);assert.equal(schemeTargetQuantitySummary(options),null);});
test("reopen Admin uses persisted authoritative amounts and retains SO reference separately",()=>{const p=plan(4);p.billing={...p.billing!,billMode:true,soBillCount:1,adminBillCount:2,soAmountWithGST:"100000",soAmountWithoutGST:"80000",amountWithGST:"118000",amountWithoutGST:"100000",bills:[{partNumber:1,soBillDate:"2026-09-12",adminBillDate:"2026-09-20",soAmountWithoutGST:"80000",soAmountWithGST:"100000",amountWithoutGST:"50000",amountWithGST:"59000",verified:true}]};const row=initialBillEditor(p,true);assert.equal(row.billCount,2);assert.equal(row.bills[0].soBillDate,"2026-09-12");assert.equal(row.bills[0].adminBillDate,"2026-09-20");assert.equal(row.bills[0].amountWithGST,"59000");assert.equal(initialBillEditor(p,false).bills[0].amountWithGST,"100000");});
for(const count of [1,2,5])test(`${count} independent bill schedules deduct booking once in highest part`,()=>{const amounts=splitBillAmount("100000",count);const schedules=amounts.map((value,i)=>billSchedule(rules,Number(value),new Date(`2026-09-${20-i}`),10000,i+1,count,5));assert.equal(schedules.flat().reduce((sum,i)=>sum+i.plannedAmount,0),90000);for(let i=0;i<count-1;i++)assert.equal(schedules[i].reduce((sum,r)=>sum+r.plannedAmount,0),Number(amounts[i]));assert.equal(schedules[0][0].plannedDate.toISOString().slice(0,10),"2026-09-25");});
test("pending final bill never moves deduction to verified Bill 1",()=>assert.deepEqual(billSchedule(rules,50000,new Date("2026-09-15"),10000,1,2,0).map(i=>i.plannedAmount),[15000,35000]));
test("later final bill receives booking independently",()=>assert.deepEqual(billSchedule(rules,50000,new Date("2026-10-15"),10000,2,2,0).map(i=>i.plannedAmount),[15000,25000]));
test("insufficient final installment rejected",()=>assert.throws(()=>billSchedule(rules,10000,new Date(),10000,2,2,0),/cannot absorb/));
test("no unverified schedule",()=>assert.throws(()=>billSchedule(rules,10000,null,0,1,1,0),/Admin-confirmed/));
test("incompatible Fixed Amount rules reject rather than prorate",()=>assert.throws(()=>billSchedule(rules.map(r=>({...r,calculationType:"FIXED_AMOUNT",value:r.value*1000})),59000,new Date(),0,1,2,0),/cannot be prorated/));
test("compatible Fixed Amount schedule unchanged",()=>assert.deepEqual(billSchedule(rules.map(r=>({...r,calculationType:"FIXED_AMOUNT",value:r.value*1000})),100000,new Date(),10000,1,1,0).map(r=>r.plannedAmount),[30000,60000]));
test("Options Amount keeps shared non-final amounts across independent part bills",()=>{const amountRules=[{installmentNumber:1,calculationType:"FIXED_AMOUNT",value:30000,daysAfterBillingDate:0},{installmentNumber:2,calculationType:"FIXED_AMOUNT",value:0,daysAfterBillingDate:30}];const first=billSchedule(amountRules,100000,new Date("2026-09-15"),10000,1,2,0,true);const final=billSchedule(amountRules,80000,new Date("2026-10-15"),10000,2,2,0,true);assert.deepEqual(first.map(r=>r.plannedAmount),[30000,70000]);assert.deepEqual(final.map(r=>r.plannedAmount),[30000,40000]);});
test("Options Amount rejects a part bill whose final balance cannot absorb booking",()=>{const amountRules=[{installmentNumber:1,calculationType:"FIXED_AMOUNT",value:30000,daysAfterBillingDate:0},{installmentNumber:2,calculationType:"FIXED_AMOUNT",value:0,daysAfterBillingDate:30}];assert.throws(()=>billSchedule(amountRules,35000,new Date(),10000,2,2,0,true),/cannot absorb/);});
test("Decimal-safe reconciliation",()=>{assertBillTotals({amountWithoutGST:"0.30",amountWithGST:"0.30"},[{amountWithoutGST:"0.10",amountWithGST:"0.10"},{amountWithoutGST:"0.20",amountWithGST:"0.20"}]);assert.throws(()=>assertBillTotals({amountWithoutGST:"0.31",amountWithGST:"0.30"},[{amountWithoutGST:"0.30",amountWithGST:"0.30"}]),/Without GST/);});
for(const count of [0,6,1.5])test(`invalid count ${count}`,()=>{assert.throws(()=>splitBillAmount("100",count));const row=billEditorPayload(initialBillEditor(plan(4),true),true);assert.equal(adminPlanBills.safeParse({...row,billCount:count}).success,false);});
for(const date of [null,"","2026-02-30","31/09/2026"])test(`invalid SO date ${date}`,()=>{const row=initialBillEditor(plan(1),false);assert.equal(soPlanBills.safeParse({...billEditorPayload(row,false),bills:[{...row.bills[0],soBillDate:date}]}).success,false);});
for(const amount of ["0","-1","NaN","Infinity","1.001"])test(`invalid amount ${amount}`,()=>{const row=billEditorPayload(initialBillEditor(plan(1),true),true);assert.equal(adminPlanBills.safeParse({...row,amountWithGST:amount}).success,false);});
test("duplicate/missing parts rejected",()=>{assert.throws(()=>assertBillParts(2,[{partNumber:1},{partNumber:1}]));assert.throws(()=>assertBillParts(2,[{partNumber:1}]));});
test("Admin null date remains pending, SO date stays required",()=>{const row=initialBillEditor(plan(1),true);assert.equal(adminPlanBills.parse(billEditorPayload(row,true)).bills[0].adminBillDate,null);});
test("calendar formatting round-trips without changing API date",()=>{assert.equal(formatSchemeDate("2026-09-12"),"12/09/2026");assert.equal(parseSchemeDate("12/09/2026"),"2026-09-12");});
console.log(`${passed} combined-plan bill contracts passed`);
